from django.urls import path
from . import views
app_name='cust'

urlpatterns=[
    path('customers_home/', views.getcustomershome,name="Customers"),
    path('abcd_home/', views.getabcdhome,name="ABCD"),
    path('masterrr_home/', views.getmasterrrhome,name="Masterrr"),
    path('change_password/', views.getchangepassword,name="ChangePassword"),
    path('my_profile/', views.getmyprofile,name="MyProfile"),
    path('settings_home/', views.getmysettingshome,name="Settings"),
    path('xyz_home/', views.getxyzhome,name="XYZ"),
    path('css1_home/', views.getcss1home,name="CSS1"),
    path('css2_home/', views.getcss2home,name="CSS2"),
    path('css3_home/', views.getcss3home,name="CSS3"),
    path('css4_home/', views.getcss4home,name="CSS4"),
    path('machinetest1_home/', views.getmachinetest1home,name="MachineTest1"),
    path('css5_home/', views.getcss5home,name="CSS5"),
    path('machinetest2_home/', views.getmachinetest2home,name="MachineTest2"),
    path('cssgridlayout_home/', views.getcssgridlayouthome,name="cssgridlayout"),
    path('cssgridlayout2_home/', views.getcssgridlayout2home,name="cssgridlayout2"),
    path('bootstrap_home/', views.getbootstraphome,name="bootstrap"),
    path('bootstrapgridsystem_home/', views.getbootstrapgridsystemhome,name="bootstrapgridsystem"),
    path('bootstrap1_home/', views.getbootstrap1home,name="bootstrap1"),
    path('bootstrap2_home/', views.getbootstrap2home,name="bootstrap2"),
    path('bootstrap3_home/', views.getbootstrap3home,name="bootstrap3"),
    path('javascript_home/', views.getjavascripthome,name="javascript"),
    path('javascript2_home/', views.getjavascript2home,name="javascript2"),
    path('javascript3_home/', views.getjavascript3home,name="javascript3"),
    path('javascript4_home/', views.getjavascript4home,name="javascript4"),
    path('javascript5_home/', views.getjavascript5home,name="javascript5"),
    path('formvalidation_home/', views.getformvalidationhome,name="formvalidation"),
    path('javascript6_home/', views.getjavascript6home,name="javascript6"),
    path('jquery_home/', views.getjqueryhome,name="jquery"),
    path('jquery2_home/', views.getjquery2home,name="jquery2"),
    path('formvalidation2_home/', views.getformvalidation2home,name="formvalidation2"),
    path('jquery3_home/', views.getjquery3home,name="jquery3"),
    path('jquery4_home/', views.getjquery4home,name="jquery4"),
    path('animations_home/', views.getanimationshome,name="animations"),
    path('json_home/', views.getjsonhome,name="json"),
    path('synchronous_home/', views.getsynchronoushome,name="synchronous"),
    path('asyncawait_home/', views.getasyncawaithome,name="asyncawait"),
]